/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: src/sanity/schema.json
export type SiteSetting = {
  _id: string;
  _type: 'siteSetting';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteName?: string;
  socialLinks?: Array<
    {
      _key: string;
    } & SocialLink
  >;
  navigation?: Array<{
    link?: PageLink;
    _type: 'navLink';
    _key: string;
  }>;
  footer?: string;
};

export type PageLink = {
  _type: 'pageLink';
  label?: string;
  href?: string;
  isInternal?: boolean;
};

export type PlatformReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'platform';
};

export type Certificate = {
  _id: string;
  _type: 'certificate';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  topics?: Array<string>;
  isFeatured?: boolean;
  mainImage?: ImageWithAlt;
  platform?: PlatformReference;
  receivedAt?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
};

export type ImageWithAlt = {
  _type: 'imageWithAlt';
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
};

export type Slug = {
  _type: 'slug';
  current?: string;
  source?: string;
};

export type Platform = {
  _id: string;
  _type: 'platform';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  mainImage?: ImageWithAlt;
};

export type History = {
  _id: string;
  _type: 'history';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  startedDate?: string;
  endedDate?: string;
  body?: BlockContent;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }>;
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'blockquote';
      listItem?: 'bullet' | 'number';
      markDefs?: Array<{
        href?: string;
        _type: 'link';
        _key: string;
      }>;
      level?: number;
      _type: 'block';
      _key: string;
    }
  | ({
      _key: string;
    } & ImageWithAlt)
>;

export type ProjectCategoryReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'projectCategory';
};

export type Project = {
  _id: string;
  _type: 'project';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  category?: ProjectCategoryReference;
  body?: BlockContent;
  details?: {
    startedDate?: string;
    endedDate?: string;
    stacks?: Array<string>;
    projectUrl?: string;
    repoUrl?: string;
  };
  mainImage?: ImageWithAlt;
};

export type ProjectCategory = {
  _id: string;
  _type: 'projectCategory';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
};

export type CategoryReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'category';
};

export type Blog = {
  _id: string;
  _type: 'blog';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  publishedAt?: string;
  minRead?: number;
  category?: CategoryReference;
  excerpt?: string;
  body?: BlockContent;
  seo?: Seo;
  mainImage?: ImageWithAlt;
};

export type Seo = {
  _type: 'seo';
  metaTitle?: string;
  metaDesc?: string;
  ogImage?: ImageWithAlt;
  noIndex?: boolean;
};

export type Category = {
  _id: string;
  _type: 'category';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
};

export type Skill = {
  _id: string;
  _type: 'skill';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  level?: number;
};

export type About = {
  _id: string;
  _type: 'about';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  body?: BlockContent;
  contactInfo?: {
    city?: string;
    state?: string;
    gitHubUrl?: string;
    linkedInURL?: string;
    leetcodeUrl?: string;
  };
  interests?: Array<string>;
};

export type SocialLink = {
  _type: 'socialLink';
  platform?: 'gitHub' | 'linkedIn' | 'leetCode';
  url?: string;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type MediaTag = {
  _id: string;
  _type: 'media.tag';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SiteSetting
  | PageLink
  | PlatformReference
  | Certificate
  | SanityImageAssetReference
  | ImageWithAlt
  | Slug
  | Platform
  | History
  | BlockContent
  | ProjectCategoryReference
  | Project
  | ProjectCategory
  | CategoryReference
  | Blog
  | Seo
  | Category
  | Skill
  | About
  | SocialLink
  | SanityImageCrop
  | SanityImageHotspot
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/query.ts
// Variable: ABOUT_QUERY
// Query: *[_type == 'about' && defined(slug.current)][0]{  "slug": slug.current,  body,  "city": contactInfo.city,  "state": contactInfo.state,  "gitHubUrl": contactInfo.gitHubUrl,  "leetCodeUrl": contactInfo.leetCodeUrl,  "linkedInUrl": contactInfo.linkedInURL,  interests[] }
export type ABOUT_QUERY_RESULT = {
  slug: string | null;
  body: BlockContent | null;
  city: string | null;
  state: string | null;
  gitHubUrl: string | null;
  leetCodeUrl: null;
  linkedInUrl: string | null;
  interests: Array<string> | null;
} | null;

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
  interface SanityQueries {
    '*[_type == \'about\'\n && defined(slug.current)][0]{\n  "slug": slug.current,\n  body,\n  "city": contactInfo.city,\n  "state": contactInfo.state,\n  "gitHubUrl": contactInfo.gitHubUrl,\n  "leetCodeUrl": contactInfo.leetCodeUrl,\n  "linkedInUrl": contactInfo.linkedInURL,\n  interests[]\n }': ABOUT_QUERY_RESULT;
  }
}
